services:
  app:
    container_name: api
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      ministack:
        condition: service_started
    restart: unless-stopped
    networks:
      - fast-feet-network

  postgres:
    container_name: database
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      retries: 5
    networks:
      - fast-feet-network

  ministack:
    container_name: ministack
    image: ministackorg/ministack
    restart: unless-stopped
    ports:
      - "4566:4566"
    networks:
      - fast-feet-network

volumes:
  pgdata:

networks:
  fast-feet-network:
    driver: bridge
