services:
  app:
    container_name: api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.development
    depends_on:
      postgres:
        condition: service_healthy
      ministack:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./scripts:/app/scripts
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./entrypoint.dev.sh:/app/entrypoint.dev.sh:cached
      - /app/node_modules
    networks:
      - fast-feet-network-dev

  postgres:
    container_name: database-dev
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      retries: 5
    networks:
      - fast-feet-network-dev

  ministack:
    container_name: ministack-dev
    image: ministackorg/ministack
    restart: unless-stopped
    ports:
      - "4566:4566"
    networks:
      - fast-feet-network-dev

volumes:
  pgdata-dev:

networks:
  fast-feet-network-dev:
    driver: bridge
